### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by Babafaba** [SeekerRook/linux_labyrinth#1]
I'm stuck at the packman level. Any hints?

**Comment by SeekerRook** [comment]
As this is a challenge I cannot give you many tips. You can check the repo wiki for commands and tools you will need to solve the challenge. If you suspect there is a bug that prevents you from solving the challenge let me know. Otherwise mark this comment as answer.

thank you again for trying this challenge.

**Comment by Babafaba** [comment]
Ok thanks
